<?php
// $Id$

/**
 * @file
 *   Shortens URLs via external services.
 */

/**
 * @todo
 * - README.txt
 * - AHAHify the block form
 */

/**
 * Implementation of hook_help().
 */
function shorten_help($path, $arg) {
  $output = '';
  switch ($path) {
    case "admin/help#shorten":
      $output = '<p>'. t("This module shortens URLs.") .'</p>';
      break;
  }
  return $output;
}

/**
 * Implementation of hook_menu().
 */
function shorten_menu() {
  $items = array();
  $items['admin/settings/shorten'] = array(
    'title' => 'Shorten settings',
    'description' => 'Adjust certain display settings for Shorten.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shorten_admin'),
    'access arguments' => array('access administration pages'),
    'file' => 'shorten.admin.inc',
  );
  return $items;
}

/**
 * Implementation of hook_block().
 */
function shorten_block($op = 'list', $delta = 0, $edit = array()) {
  if ($op == 'list') {
    $block['shorten']['info'] = t('Shorten URLs');
    return $block;
  }
  else if ($op == 'view' && $delta == 'shorten') {
    $block['subject'] = t('Shorten URLs');
    $block['content'] = shorten_form_display();
    return $block;
  }
  else if ($op == 'configure' && $delta == 'shorten') {
    $methods = array();
    if (function_exists('file_get_contents')) {
      $methods['php'] = t('PHP');
    }
    if (function_exists('curl_exec')) {
      $methods['curl'] = t('cURL');
    }
    if (!empty($methods)) {
      $form['shorten_show_service'] = array(
        '#type' => 'checkbox',
        '#title' => t('Show the list of URL shortening services'),
        '#default_value' => variable_get('shorten_show_service', FALSE),
        '#weight' => -4,
      );
      return $form;
    }
  }
  else if ($op == 'save' && $delta == 'shorten') {
    variable_set('shorten_show_service', $edit['shorten_show_service']);
  }
}

/**
 * Retrieves and beautifies the abbreviated URL.
 * This is the main API function of this module.
 *
 * @param $original
 *   The URL of the page for which to create the abbreviated URL.  If not passed
 *   uses the current page.
 * @param $service
 *   The service to use to abbreviate the URL.
 *   For services available by default, see shorten_shorten_service().
 * @return
 *   An abbreviated URL.
 */
function shorten_shorten($original = '', $service = '') {
  if (!$original) {
    global $base_url;
    $original = $base_url . base_path() . $_GET['q'];
  }
  if (!$service) {
    $service = variable_get('shorten_service', 'is.gd');
  }
  $cached = cache_get($original);
  if ($cached->data) {
    return $cached->data;
  }
  $url = _shorten_get_url($original, $service);
  //If the primary service fails, try the secondary service.
  if (!$url) {
    $url = _shorten_get_url($original, variable_get('shorten_service_backup', 'TinyURL'));
    //If the secondary service fails, use the original URL.
    if (!$url) {
      $url = $original;
    }
  }
  //Replace "http://" with "www." if the URL is abbreviated because it's shorter.
  if ($url != $original && variable_get('shorten_www', TRUE)) {
    $url = drupal_substr($url, 7);
    $url = 'www.'. $url;
  }
  $expire = time() + (60 * 60 * 24 * 7 * 3);
  cache_set($original, $url, 'cache', $expire);
  return $url;
}

/**
 * Shortens URLs. Times out after three (3) seconds.
 *
 * @param $original
 *   The URL of the page for which to retrieve the abbreviated URL.
 * @param $service
 *   The service to use to abbreviate the URL.
 *   For services available by default, see shorten_shorten_service().
 * @return
 *   An abbreviated URL.
 */
function _shorten_get_url($original, $service) {
  $method = drupal_strtoupper(variable_get('shorten_method', 'curl'));
  $services = module_invoke_all('shorten_service', $original);
  foreach ($services as $name => $api) {
    if ($service == $name) {
      if (is_string($api)) {
        $url = shorten_fetch($api . $original);
        break;
      }
      else if (is_array($api) && $api['custom'] === 'xml') {
        $url = shorten_fetch($api['url'] . $original, $api['tag']);
        break;
      }
      else if (is_array($api) && $api['custom'] === FALSE) {
        $url = shorten_fetch($api['url'] . $original);
        break;
      }
      else if (is_array($api) && $api['custom'] === TRUE) {
        $url = $api['url'];
        $method = t('A custom method');
        break;
      }
    }
  }
  //If the service isn't found, use the original.
  if (!$url) {
    return $original;
  }

  if ($url && drupal_substr($url, 0, 7) == 'http://') {
    return $url;
  }
  watchdog('shorten', '%method failed to return an abbreviated URL from %service.', array('%method' => $method, '%service' => $service), WATCHDOG_NOTICE, $url);
  return FALSE;
}

/**
 * Implementation of hook_shorten_service().
 */
function shorten_shorten_service($original) {
  return array(
    'cli.gs' => 'http://cli.gs/api/v1/cligs/create?appid=drupal&url=',
    'hex.io' => 'http://hex.io/api-create.php?url=',
    'idek.net' => 'http://idek.net/c.php?idek-api=true&idek-ref=drupal_shorten_module&idek-url=',
    'is.gd' => 'http://is.gd/api.php?longurl=',
    'lin.cr' => 'http://lin.cr/?mode=api&full=1&l=',
    'Metamark' => 'http://metamark.net/api/rest/simple?long_url=',
    'PiURL' => 'http://piurl.com/api.php?url=',
    'ri.ms' => 'http://ri.ms/api-create.php?url=',
    'short.ie' => array(
      'custom' => 'xml',
      'url' => 'http://short.ie/api?url=',
      'tag' => 'shortened',
    ),
    'th8.us' => 'http://th8.us/api.php?url=',
    'TinyURL' => 'http://tinyurl.com/api-create.php?url=',
    'tr.im' => 'http://api.tr.im/api/trim_simple?url=',
    'urlb.at' => 'http://urlb.at/api/rest/?url=',
    'urlCover' => 'http://urlcover.com/api.php?link=',
  );
  //The following services require API keys, and so are not normally used in
  //this module. Replace the relevant variables in the URLs below and move to
  //the above array to use.
  $other = array(
    'Adjix.com' => "http://api.adjix.com/shrinkLink?ultraShort=y&partnerID=$adjix_id&url=",
    'bit.ly' => array(
      'custom' => 'xml',
      'url' => "http://api.bit.ly/shorten?version=2.0.1&format=xml&login=$bitly_name&apiKey=$bitly_key&longUrl=",
    ),
  );
  //When tested on May 9, 2009, snurl worked, but the documentation says it's
  //deprecated, so it could be removed at any time. WapURL will soon require
  //registration to use according to the documentation.
  $deprecated = array(
    'snurl' => 'http://snipurl.com/site/snip?r=simple&link=',
    'WapURL' => 'http://wapURL.co.uk//api.cfm?URLToConvert=',
  );
  //Shorten cannot and will not handle $_POST requests.
}

/**
 * Downloads the response of the URL abbreviation service.
 *
 * @param $url
 *   The URL which will return an abbreviated URL from any service. Includes
 *   both the service and the URL to be shortened.
 * @param $tag
 *   If the response is XML, the tag within which to look for the shortened URL.
 * @return
 *   An abbreviated URL or the original one if fetching methods are unavailable.
 */
function shorten_fetch($url, $tag = '') {
  if (variable_get('shorten_method', 'curl') == 'php') {
    $context = stream_context_create(array('http' => array('timeout' => 3))); 
    $contents = file_get_contents($url, 0, $context);
  }
  else if (variable_get('shorten_method', 'curl') == 'curl') {
    $c = curl_init();
    curl_setopt($c, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($c, CURLOPT_CONNECTTIMEOUT, 3);
    curl_setopt($c, CURLOPT_URL, $url);
    $contents = curl_exec($c);
    curl_close($c);
  }
  else {
    $contents = $url;
  }
  if ($tag) {
    $contents = _shorten_xml($contents, $tag);
  }
  return $contents;
}

/**
 * Parses the value between tags in an XML document.
 *
 * @param $xml
 *   The contents of the XML document.
 * @param $tag
 *   The tag to get the value from.
 * @return
 *   The value from the specified tag, typically an abbreviated URL.
 */
function _shorten_xml($xml, $tag) {
  $start = strpos($xml, $tag) + drupal_strlen($tag) + 1;
  $end = strpos($xml, $tag, $start + 1) - 2;
  $length = -(drupal_strlen($xml) - $end);
  return drupal_substr($xml, $start, $length);
}

/**
 * Displays the Shorten form.
 */
function shorten_form_display() {
  return drupal_get_form('shorten_form_shorten');
}

/**
 * Form which allows shortening of a URL via the UI.
 */
function shorten_form_shorten() {
  $form['url'] = array(
    '#type' => 'textfield',
    '#title' => t('URL'),
    '#default_value' => '',
    '#required' => TRUE,
    '#size' => 25,
  );
  $service = _shorten_service_form();
  if (is_array($service)) {
    $form['service'] = $service;
  }
  $form['shorten'] = array(
    '#type' => 'submit',
    '#value' => t('Shorten'),
  );
  return $form;
}

/**
 * Validate function for the Shorten form.
 */
function shorten_form_shorten_validate($form, &$form_state) {
  $url = $form_state['values']['url'];
  if (drupal_substr($url, 0, 7) != 'http://' && drupal_substr($url, 0, 8) != 'https://' && strpos($url, '.', 9)) {
    form_set_error('url', t('Please enter a valid URL.'));
  }
}

/**
 * Submit function for the Shorten form.
 */
function shorten_form_shorten_submit($form, &$form_state) {
  $service = '';
  if ($form_state['values']['service']) {
    $service = $form_state['values']['service'];
  }
  $shortened = shorten_shorten($form_state['values']['url'], $service);
  drupal_set_message(t('%original was shortened to %shortened', array('%original' => $form_state['values']['url'], '%shortened' => $shortened)));
}

/**
 * Form which displays a list of URL shortening services.
 */
function _shorten_service_form() {
  if (variable_get('shorten_show_service', FALSE)) {
    $methods = array();
    if (function_exists('file_get_contents')) {
      $methods['php'] = t('PHP');
    }
    if (function_exists('curl_exec')) {
      $methods['curl'] = t('cURL');
    }
    if (!empty($methods)) {
      $all_services = module_invoke_all('shorten_service', $original);
      $services = array();
      foreach ($all_services as $key => $value) {
        $services[$key] = $key;
      }
      $default = variable_get('shorten_service', 'is.gd');
      if ($default == 'none') {
        $default = 'TinyURL';
      }
      return array(
        '#type' => 'select',
        '#title' => t('Service'),
        '#description' => t('The service to use to shorten the URL.'),
        '#default_value' => $default,
        '#options' => $services,
      );
    }
  }
}